# Generated by Django 5.1.7 on 2025-04-03 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион')),
                ('full_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс')),
                ('farmer', models.CharField(blank=True, max_length=500, null=True, verbose_name='Фермер')),
                ('status', models.CharField(choices=[('Free', 'Свободная'), ('Not_contact', 'Нет контакта'), ('Agreed', 'Создана заявка')], max_length=40, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Фермер',
                'verbose_name_plural': 'Фермеры',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not_processed', 'Не обработан'), ('Primary_contact', 'Первичный контакт'), ('Refusal', 'Отказ'), ('Freezing', 'Заморозка'), ('Approval', 'На согласование'), ('Agreed', 'Согласовано'), ('Not_agreed', 'Не согласовано'), ('Revision', 'Отправлен на доработку')], max_length=40, verbose_name='Статус')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('product', models.CharField(blank=True, max_length=155, null=True, verbose_name='Товар')),
                ('point_loading', models.CharField(blank=True, max_length=255, null=True, verbose_name='Точка выгрузки')),
                ('product_quality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Качество товара')),
                ('price_nds', models.FloatField(blank=True, null=True, verbose_name='Цена СХТП')),
                ('nds', models.IntegerField(blank=True, null=True, verbose_name='НДС')),
                ('terms_payment', models.CharField(blank=True, max_length=155, null=True, verbose_name='Условия оплаты')),
                ('date_delivery', models.DateField(blank=True, null=True, verbose_name='Срок поставки')),
                ('daily_loading_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Суточная норма погрузки')),
                ('transport', models.IntegerField(blank=True, null=True, verbose_name='Транспорт')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Расстояние')),
                ('Price_per_ton', models.IntegerField(blank=True, null=True, verbose_name='Цена за тн')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.farmer', verbose_name='Фермер')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='FarmerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Phone', 'Телефон'), ('Mail', 'Почта')], default='Phone', max_length=155, verbose_name='Тип')),
                ('contact', models.CharField(max_length=155, verbose_name='Контакт')),
                ('is_work', models.CharField(choices=[('work', 'Рабочий'), ('not_work', 'Не рабочий'), ('undefined', 'Не определен')], default='undefined', max_length=40, verbose_name='Рабочий?')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.farmer', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Контакт фермера',
                'verbose_name_plural': 'Контакты фермеров',
            },
        ),
        migrations.CreateModel(
            name='HistoryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('dsc', models.TextField(verbose_name='Примечание')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'История созвона',
                'verbose_name_plural': 'История созвонов',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Менеджер'), (2, 'Директор'), (3, 'Директор по логистике'), (4, 'Директор менеджеров')], verbose_name='Роль')),
                ('plan_work', models.CharField(blank=True, max_length=255, null=True, verbose_name='План работ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='manage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.profile', verbose_name='Менеджер'),
        ),
    ]
