# Generated by Django 5.1.7 on 2025-04-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('manage', models.CharField(max_length=30, verbose_name='Пароль для менеджера')),
                ('total_manage', models.CharField(max_length=30, verbose_name='Пароль для старшего менеджера')),
            ],
            options={
                'verbose_name': 'Корпоративный пароль',
                'verbose_name_plural': 'Корпоративные пароли',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Менеджер'), (2, 'Директор'), (3, 'Директор по логистике'), (4, 'Старший менеджер')], verbose_name='Роль'),
        ),
    ]
