# Generated by Django 5.1.7 on 2025-04-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_corppassword_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='status',
            field=models.CharField(choices=[('Free', 'Свободный'), ('Not_contact', 'Нет контакта'), ('Agreed', 'Создана заявка')], max_length=40, verbose_name='Статус'),
        ),
    ]
