# Generated by Django 5.1.7 on 2025-04-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_farmer_farmer_alter_farmer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем'),
        ),
    ]
