# Generated by Django 5.1.7 on 2025-04-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_application_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Price_per_ton',
        ),
        migrations.AlterField(
            model_name='application',
            name='distance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='application',
            name='nds',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='application',
            name='price_nds',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена СХТП'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Not_processed', 'Не обработан'), ('Primary_contact', 'Первичный контакт'), ('Refusal', 'Отказ'), ('Freezing', 'Заморозка'), ('Approval', 'На согласовании'), ('Agreed', 'Согласовано'), ('Not_agreed', 'Не согласовано'), ('Revision', 'Отправлен на доработку')], max_length=40, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transport',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Транспорт'),
        ),
        migrations.AddField(
            model_name='application',
            name='price_per_ton',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена за тн'),
        ),
    ]
