# Generated by Django 5.1.7 on 2025-04-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_remove_application_price_per_ton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Not_processed', 'Не обработан'), ('Primary_contact', 'Первичный контакт'), ('Refusal', 'Отказ'), ('Freezing', 'Заморозка'), ('Approval', 'На согласовании'), ('Agreed', 'Согласовано'), ('Not_agreed', 'Не согласовано'), ('Revision', 'Отправлен на доработку')], default='Not_processed', max_length=40, verbose_name='Статус'),
        ),
    ]
