# Generated by Django 5.1.7 on 2025-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_alter_application_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='data_end',
            field=models.CharField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='application',
            name='data_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата дедлайна'),
        ),
        migrations.AddField(
            model_name='application',
            name='data_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
