# Generated by Django 5.1.7 on 2025-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_application_data_end_application_data_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='full_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адресс'),
        ),
    ]
