# Generated by Django 5.1.7 on 2025-04-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_farmer_farmer_alter_farmer_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='full_address',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Адресс'),
        ),
    ]
