# Generated by Django 5.1.7 on 2025-04-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_farmer_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmercontact',
            name='contact',
            field=models.CharField(max_length=500, verbose_name='Контакт'),
        ),
    ]
