# Generated by Django 5.1.7 on 2025-04-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_farmercontact_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='data_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
