# Generated by Django 5.1.7 on 2025-04-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_application_data_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата передачи')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.application', verbose_name='Заявка')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='server.profile', verbose_name='Кто передает')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='server.profile', verbose_name='Кому передает')),
            ],
            options={
                'verbose_name': 'История передачи заявки',
                'verbose_name_plural': 'Истории передачи заявок',
            },
        ),
    ]
