# Generated by Django 5.1.7 on 2025-04-08 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_applicationtransferhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtransferhistory',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to=settings.AUTH_USER_MODEL, verbose_name='Кто передает'),
        ),
        migrations.AlterField(
            model_name='applicationtransferhistory',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to=settings.AUTH_USER_MODEL, verbose_name='Кому передает'),
        ),
    ]
