# Generated by Django 5.1.7 on 2025-04-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_applicationtransferhistory_from_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование региона')),
                ('manage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.profile', verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
    ]
