# Generated by Django 5.1.7 on 2025-04-15 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.region', verbose_name='Регион'),
        ),
    ]
