# Generated by Django 5.1.7 on 2025-04-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_farmer_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='address',
        ),
    ]
