# Generated by Django 5.1.7 on 2025-05-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_remove_farmer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='historycontact',
            name='type',
            field=models.CharField(blank=True, choices=[('Call', 'Звонок'), ('Note', 'Примечание'), ('Notification', 'Уведомление')], default='Call', max_length=20, null=True, verbose_name='Тип'),
        ),
    ]
