# Generated by Django 5.1.7 on 2025-05-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_historycontact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historycontact',
            name='data_call',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата созвона'),
        ),
    ]
